INSERT INTO compta.pcg_accounts (number, label, system, parent) VALUES
('1', 'Comptes de capitaux', 'minimal', NULL),
('2', 'Comptes d''immobilisations', 'minimal', NULL),
('3', 'Comptes de stocks et en-cours', 'minimal', NULL),
('4', 'Comptes de tiers', 'minimal', NULL),
('5', 'Comptes financiers', 'minimal', NULL),
('6', 'Comptes de charges', 'minimal', NULL),
('7', 'Comptes de produits', 'minimal', NULL),
('10', 'Capital et réserves', 'minimal', '1'),
('11', 'Report à nouveau', 'minimal', '1'),
('12', 'Résultat de l''exercice', 'minimal', '1'),
('13', 'Subventions d''investissement', 'minimal', '1'),
('14', 'Provisions réglementées', 'minimal', '1'),
('15', 'Provisions', 'minimal', '1'),
('16', 'Emprunts et dettes assimilées, fonds non remboursables et avances conditionnées', 'minimal', '1'),
('17', 'Dettes rattachées à des participations', 'minimal', '1'),
('18', 'Comptes de liaison des établissements et sociétés en participation', 'minimal', '1'),
('20', 'Immobilisations incorporelles et frais d’établissement', 'minimal', '2'),
('21', 'Immobilisations corporelles', 'minimal', '2'),
('22', 'Immobilisations mises en concession', 'minimal', '2'),
('23', 'Immobilisations en cours, avances et acomptes', 'minimal', '2'),
('26', 'Participations et créances rattachées à des participations', 'minimal', '2'),
('27', 'Autres immobilisations financières', 'minimal', '2'),
('28', 'Amortissements des immobilisations', 'minimal', '2'),
('29', 'Dépréciations des immobilisations', 'minimal', '2'),
('31', 'Matières premières et fournitures', 'minimal', '3'),
('32', 'Autres approvisionnements', 'minimal', '3'),
('33', 'En-cours de production de biens', 'minimal', '3'),
('34', 'En-cours de production de services', 'minimal', '3'),
('35', 'Stocks de produits', 'minimal', '3'),
('36', '(Compte à ouvrir, le cas échéant, sous l''intitulé « Stocks provenant d''immobilisations »)', 'minimal', '3'),
('37', 'Stocks de marchandises', 'minimal', '3'),
('38', '(Le compte 38 peut être utilisé pour comptabiliser les stocks en voie d''acheminement, mis en dépôt ou donnés en consignation)', 'minimal', '3'),
('39', 'Dépréciations des stocks et en-cours', 'minimal', '3'),
('40', 'Fournisseurs et comptes rattachés', 'minimal', '4'),
('41', 'Clients et comptes rattachés', 'minimal', '4'),
('42', 'Personnel et comptes rattachés', 'minimal', '4'),
('43', 'Sécurité sociale et autres organismes sociaux', 'minimal', '4'),
('44', 'État et autres collectivités publiques', 'minimal', '4'),
('45', 'Groupe et associés', 'minimal', '4'),
('46', 'Débiteurs divers et créditeurs divers', 'minimal', '4'),
('47', 'Comptes transitoires ou d''attente', 'minimal', '4'),
('48', 'Comptes de régularisation', 'minimal', '4'),
('49', 'Dépréciations des comptes de tiers', 'minimal', '4'),
('50', 'Valeurs mobilières de placement', 'minimal', '5'),
('51', 'Banques, établissements financiers et assimilés', 'minimal', '5'),
('52', 'Instruments financiers à terme et jetons détenus', 'minimal', '5'),
('53', 'Caisse', 'minimal', '5'),
('58', 'Virements internes', 'minimal', '5'),
('59', 'Dépréciations des comptes financiers', 'minimal', '5'),
('60', 'Achats (sauf 603)', 'minimal', '6'),
('61', 'Services extérieurs', 'minimal', '6'),
('62', 'Autres services extérieurs', 'minimal', '6'),
('63', 'Impôts, taxes et versements assimilés', 'minimal', '6'),
('64', 'Charges de personnel', 'minimal', '6'),
('65', 'Autres charges de gestion courante', 'minimal', '6'),
('66', 'Charges financières', 'minimal', '6'),
('67', 'Charges exceptionnelles', 'minimal', '6'),
('68', 'Dotations aux amortissements, aux dépréciations et aux provisions', 'minimal', '6'),
('69', 'Participation des salariés - Impôts sur les bénéfices et assimilés', 'minimal', '6'),
('70', 'Ventes de produits fabriqués, prestations de services, marchandises', 'minimal', '7'),
('71', 'Production stockée (ou déstockage)', 'minimal', '7'),
('72', 'Production immobilisée', 'minimal', '7'),
('74', 'Subventions', 'minimal', '7'),
('75', 'Autres produits de gestion courante', 'minimal', '7'),
('76', 'Produits financiers', 'minimal', '7'),
('77', 'Produits exceptionnels', 'minimal', '7'),
('78', 'Reprises sur amortissements, dépréciations et provisions', 'minimal', '7')
ON CONFLICT (number) DO NOTHING;