INSERT INTO compta.pcg_accounts (number, label, system, parent) VALUES
('505', 'Obligations et bons émis par la société et rachetés par elle', 'minimal', '50'),
('506', 'Obligations', 'minimal', '50'),
('507', 'Bons du Trésor et bons de caisse à court terme', 'minimal', '50'),
('508', 'Autres valeurs mobilières de placement et autres créances assimilées', 'minimal', '50'),
('509', 'Versements restant à effectuer sur valeurs mobilières de placement non libérées', 'minimal', '50'),
('511', 'Valeurs à l''encaissement', 'minimal', '51'),
('512', 'Banques', 'minimal', '51'),
('517', 'Autres organismes financiers', 'minimal', '51'),
('518', 'Intérêts courus', 'minimal', '51'),
('519', 'Concours bancaires courants', 'minimal', '51'),
('521', 'Instruments financiers à terme', 'minimal', '52'),
('522', 'Jetons détenus', 'minimal', '52'),
('523', 'Jetons auto-détenus', 'minimal', '52'),
('524', 'Jetons empruntés', 'minimal', '52'),
('590', 'Dépréciations des valeurs mobilières de placement', 'minimal', '59'),
('601', 'Achats stockés - Matières premières et fournitures', 'minimal', '60'),
('602', 'Achats stockés - Autres approvisionnements', 'minimal', '60'),
('603', 'Variation des stocks d''approvisionnements et de marchandises', 'minimal', '60'),
('604', 'Achats d''études et prestations de services', 'minimal', '60'),
('605', 'Achats de matériel, équipements et travaux', 'minimal', '60'),
('606', 'Achats non stockés de matière et fournitures', 'minimal', '60'),
('607', 'Achats de marchandises', 'minimal', '60'),
('608', '(Compte réservé, le cas échéant, au regroupement des frais accessoires incorporés aux achats)', 'minimal', '60'),
('609', 'Rabais, remises et ristournes obtenus sur achats (même ventilation que celle du compte 60)', 'minimal', '60'),
('611', 'Sous-traitance générale', 'minimal', '61'),
('612', 'Redevances de crédit-bail', 'minimal', '61'),
('613', 'Locations', 'minimal', '61'),
('614', 'Charges locatives et de copropriété', 'minimal', '61'),
('615', 'Entretien et réparation', 'minimal', '61'),
('616', 'Primes d''assurances', 'minimal', '61'),
('617', 'Études et recherches', 'minimal', '61'),
('618', 'Divers', 'minimal', '61'),
('619', 'Rabais, remises et ristournes obtenus sur services extérieurs', 'minimal', '61'),
('621', 'Personnel extérieur à l''entité', 'minimal', '62'),
('622', 'Rémunérations d''intermédiaires et honoraires', 'minimal', '62'),
('623', 'Publicité, publications, relations publiques', 'minimal', '62'),
('624', 'Transports de biens et transports collectifs du personnel', 'minimal', '62'),
('625', 'Déplacements, missions et réceptions', 'minimal', '62'),
('626', 'Frais postaux et de télécommunications', 'minimal', '62'),
('627', 'Services bancaires et assimilés', 'minimal', '62'),
('628', 'Divers', 'minimal', '62'),
('629', 'Rabais, remises et ristournes obtenus sur autres services extérieurs', 'minimal', '62'),
('631', 'Impôts, taxes et versements assimilés sur rémunérations (administrations des impôts)', 'minimal', '63'),
('633', 'Impôts, taxes et versements assimilés sur rémunérations (autres organismes)', 'minimal', '63'),
('635', 'Autres impôts, taxes et versements assimilés (administrations des impôts)', 'minimal', '63'),
('637', 'Autres impôts, taxes et versements assimilés (autres organismes)', 'minimal', '63'),
('638', 'Rappel d’impôts (autres qu’impôts sur les bénéfices)', 'minimal', '63'),
('641', 'Rémunérations du personnel', 'minimal', '64'),
('644', 'Rémunération du travail de l''exploitant', 'facultatif', '64'),
('645', 'Cotisations de sécurité sociale et de prévoyance', 'minimal', '64'),
('646', 'Cotisations sociales personnelles de l''exploitant', 'facultatif', '64'),
('647', 'Autres cotisations sociales', 'minimal', '64'),
('648', 'Autres charges de personnel', 'minimal', '64'),
('649', 'Remboursements de charges de personnel', 'minimal', '64'),
('651', 'Redevances pour concessions, brevets, licences, marques, procédés, solutions informatiques, droits et valeurs similaires', 'minimal', '65'),
('653', 'Rémunérations de l’activité des administrateurs et des gérants', 'minimal', '65'),
('654', 'Pertes sur créances irrécouvrables', 'minimal', '65'),
('655', 'Quote-part de résultat sur opérations faites en commun', 'minimal', '65'),
('656', 'Pertes de change sur créances et dettes commerciales', 'minimal', '65'),
('657', 'Valeurs comptables des immobilisations incorporelles et corporelles cédées', 'minimal', '65'),
('658', 'Pénalités et autres charges', 'minimal', '65'),
('661', 'Charges d''intérêts', 'minimal', '66'),
('664', 'Pertes sur créances liées à des participations', 'minimal', '66'),
('665', 'Escomptes accordés', 'minimal', '66'),
('666', 'Pertes de change financières', 'minimal', '66'),
('667', 'Charges sur cession d’éléments financiers', 'minimal', '66'),
('668', 'Autres charges financières', 'minimal', '66'),
('672', '(Compte à la disposition des entités pour enregistrer, en cours d''exercice, les charges sur exercices antérieurs)', 'minimal', '67'),
('678', 'Autres charges exceptionnelles', 'minimal', '67'),
('681', 'Dotations aux amortissements, aux dépréciations et aux provisions (à inscrire dans les charges d''exploitation)', 'minimal', '68'),
('686', 'Dotations aux amortissements, aux dépréciations et aux provisions (à inscrire dans les charges financières)', 'minimal', '68'),
('687', 'Dotations aux amortissements, aux dépréciations et aux provisions (à inscrire dans les charges exceptionnelles)', 'minimal', '68'),
('691', 'Participation des salariés aux résultats', 'minimal', '69'),
('695', 'Impôts sur les bénéfices', 'minimal', '69'),
('696', 'Suppléments d''impôt sur les sociétés liés aux distributions', 'minimal', '69'),
('698', 'Intégration fiscale', 'minimal', '69'),
('699', 'Produits - Reports en arrière des déficits', 'minimal', '69'),
('701', 'Ventes de produits finis', 'minimal', '70'),
('702', 'Ventes de produits intermédiaires', 'minimal', '70'),
('703', 'Ventes de produits résiduels', 'minimal', '70'),
('704', 'Travaux', 'minimal', '70'),
('705', 'Études', 'minimal', '70'),
('706', 'Prestations de services', 'minimal', '70'),
('707', 'Ventes de marchandises', 'minimal', '70'),
('708', 'Produits des activités annexes', 'minimal', '70'),
('709', 'Rabais, remises et ristournes accordés', 'minimal', '70'),
('713', 'Variation des stocks des en-cours de production et de produits', 'minimal', '71'),
('721', 'Immobilisations incorporelles', 'minimal', '72'),
('722', 'Immobilisations corporelles', 'minimal', '72'),
('741', 'Subventions d’exploitation', 'minimal', '74'),
('742', 'Subventions d’équilibre', 'minimal', '74'),
('747', 'Quote-part des subventions d’investissement virée au résultat de l’exercice', 'minimal', '74'),
('751', 'Redevances pour concessions, brevets, licences, marques, procédés, solutions informatiques, droits et valeurs similaires', 'minimal', '75'),
('752', 'Revenus des immeubles non affectés à des activités professionnelles', 'minimal', '75'),
('753', 'Rémunérations de l’activité des administrateurs et des gérants', 'minimal', '75'),
('754', 'Ristournes perçues des coopératives provenant des excédents', 'minimal', '75'),
('755', 'Quote-part de résultat sur opérations faites en commun', 'minimal', '75'),
('756', 'Gains de change sur créances et dettes commerciales', 'minimal', '75'),
('757', 'Produits des cessions d’immobilisations incorporelles et corporelles', 'minimal', '75'),
('758', 'Indemnités et autres produits', 'minimal', '75'),
('761', 'Produits de participations', 'minimal', '76'),
('762', 'Produits des autres immobilisations financières', 'minimal', '76'),
('763', 'Revenus des autres créances', 'minimal', '76'),
('764', 'Revenus des valeurs mobilières de placement', 'minimal', '76'),
('765', 'Escomptes obtenus', 'minimal', '76'),
('766', 'Gains de change financiers', 'minimal', '76'),
('767', 'Produits sur cession d’éléments financiers', 'minimal', '76'),
('768', 'Autres produits financiers', 'minimal', '76'),
('772', '(Compte à la disposition des entités pour enregistrer, en cours d''exercice, les produits sur exercices antérieurs)', 'minimal', '77'),
('778', 'Autres produits exceptionnels', 'minimal', '77'),
('781', 'Reprises sur amortissements, dépréciations et provisions (à inscrire dans les produits d''exploitation)', 'minimal', '78'),
('786', 'Reprises sur dépréciations et provisions (à inscrire dans les produits financiers)', 'minimal', '78'),
('787', 'Reprises sur dépréciations et provisions (à inscrire dans les produits exceptionnels)', 'minimal', '78'),
('1011', 'Capital souscrit - non appelé', 'facultatif', '101'),
('1012', 'Capital souscrit - appelé, non versé', 'facultatif', '101'),
('1013', 'Capital souscrit - appelé, versé', 'facultatif', '101'),
('1018', 'Capital souscrit soumis à des réglementations particulières', 'facultatif', '101'),
('1041', 'Primes d''émission', 'facultatif', '104'),
('1042', 'Primes de fusion', 'facultatif', '104'),
('1043', 'Primes d''apport', 'facultatif', '104'),
('1044', 'Primes de conversion d''obligations en actions', 'facultatif', '104'),
('1045', 'Bons de souscription de titres en capital', 'facultatif', '104'),
('1061', 'Réserve légale', 'minimal', '106'),
('1062', 'Réserves indisponibles', 'minimal', '106'),
('1063', 'Réserves statutaires ou contractuelles', 'minimal', '106'),
('1064', 'Réserves réglementées', 'minimal', '106'),
('1068', 'Autres réserves', 'minimal', '106'),
('1209', 'Acomptes sur dividendes', 'facultatif', '120'),
('1511', 'Provisions pour litiges', 'facultatif', '151'),
('1512', 'Provisions pour garanties données aux clients', 'facultatif', '151'),
('1514', 'Provisions pour amendes et pénalités', 'facultatif', '151'),
('1515', 'Provisions pour pertes de change', 'facultatif', '151'),
('1516', 'Provisions pour pertes sur contrats', 'facultatif', '151'),
('1518', 'Autres provisions pour risques', 'facultatif', '151'),
('1521', 'Provisions pour pensions et obligations similaires', 'facultatif', '152'),
('1522', 'Provisions pour restructurations', 'facultatif', '152'),
('1523', 'Provisions pour impôts', 'facultatif', '152'),
('1524', 'Provisions pour renouvellement des immobilisations - entreprises concessionnaires', 'facultatif', '152'),
('1525', 'Provisions pour gros entretien ou grandes révisions', 'facultatif', '152'),
('1526', 'Provisions pour remise en état', 'facultatif', '152'),
('1527', 'Autres provisions pour charges', 'facultatif', '152'),
('1618', 'Intérêts courus sur emprunts obligataires convertibles', 'facultatif', '161'),
('1638', 'Intérêts courus sur autres emprunts obligataires', 'facultatif', '163'),
('1648', 'Intérêts courus sur emprunts auprès des établissements de crédit', 'facultatif', '164'),
('1651', 'Dépôts', 'facultatif', '165'),
('1655', 'Cautionnements', 'facultatif', '165'),
('1658', 'Intérêts courus sur dépôts et cautionnements reçus', 'facultatif', '165'),
('1661', 'Comptes bloqués', 'facultatif', '166'),
('1662', 'Fonds de participation', 'facultatif', '166'),
('1668', 'Intérêts courus sur participation des salariés aux résultats', 'facultatif', '166')
ON CONFLICT (number) DO NOTHING;