INSERT INTO compta.pcg_accounts (number, label, system, parent) VALUES
('101', 'Capital', 'minimal', '10'),
('102', 'Fonds fiduciaires', 'facultatif', '10'),
('104', 'Primes liées au capital', 'minimal', '10'),
('105', 'Écarts de réévaluation', 'minimal', '10'),
('106', 'Réserves', 'minimal', '10'),
('107', 'Écart d''équivalence', 'minimal', '10'),
('108', 'Compte de l''exploitant', 'minimal', '10'),
('109', 'Actionnaires : capital souscrit - non appelé', 'minimal', '10'),
('110', 'Report à nouveau - solde créditeur', 'minimal', '11'),
('119', 'Report à nouveau - solde débiteur', 'minimal', '11'),
('120', 'Résultat de l''exercice - bénéfice', 'minimal', '12'),
('129', 'Résultat de l''exercice – perte', 'minimal', '12'),
('131', 'Subventions d''investissement octroyées', 'minimal', '13'),
('139', 'Subventions d''investissement inscrites au compte de résultat', 'minimal', '13'),
('143', 'Provisions réglementées pour hausse de prix', 'minimal', '14'),
('145', 'Amortissements dérogatoires', 'minimal', '14'),
('148', 'Autres provisions réglementées', 'minimal', '14'),
('151', 'Provisions pour risques', 'minimal', '15'),
('152', 'Provisions pour charges', 'minimal', '15'),
('161', 'Emprunts obligataires convertibles si non-inscrits dans le compte 167', 'minimal', '16'),
('162', 'Obligations représentatives de passifs nets remis en fiducie si non-inscrites dans le compte 167', 'minimal', '16'),
('163', 'Autres emprunts obligataires si non-inscrits dans le compte 167', 'minimal', '16'),
('164', 'Emprunts auprès des établissements de crédit si non-inscrits dans le compte 167', 'minimal', '16'),
('165', 'Dépôts et cautionnements reçus', 'minimal', '16'),
('166', 'Participation des salariés aux résultats', 'minimal', '16'),
('167', 'Fonds non remboursables et avances conditionnées', 'minimal', '16'),
('168', 'Autres emprunts et dettes assimilées', 'minimal', '16'),
('169', 'Primes de remboursement des emprunts', 'minimal', '16'),
('171', 'Dettes rattachées à des participations - groupe', 'facultatif', '17'),
('174', 'Dettes rattachées à des participations - hors groupe', 'facultatif', '17'),
('178', 'Dettes rattachées à des sociétés en participation', 'facultatif', '17'),
('181', 'Comptes de liaison des établissements', 'facultatif', '18'),
('186', 'Biens et prestations de services échangés entre établissements - charges', 'facultatif', '18'),
('187', 'Biens et prestations de services échangés entre établissements - produits', 'facultatif', '18'),
('188', 'Comptes de liaison des sociétés en participation', 'facultatif', '18'),
('201', 'Frais d''établissement', 'minimal', '20'),
('203', 'Frais de développement', 'minimal', '20'),
('205', 'Concessions et droits similaires, brevets, licences, marques, procédés, solutions informatiques, droits et valeurs similaires', 'minimal', '20'),
('206', 'Droit au bail', 'minimal', '20'),
('207', 'Fonds commercial', 'minimal', '20'),
('208', 'Autres immobilisations incorporelles', 'minimal', '20'),
('211', 'Terrains', 'minimal', '21'),
('212', 'Agencements et aménagements de terrains (même ventilation que celle du compte 211)', 'minimal', '21'),
('213', 'Constructions', 'minimal', '21'),
('214', 'Constructions sur sol d''autrui (même ventilation que celle du compte 213)', 'minimal', '21'),
('215', 'Installations techniques, matériels et outillages industriels', 'minimal', '21'),
('218', 'Autres immobilisations corporelles', 'minimal', '21'),
('229', 'Droits du concédant (présentés dans la rubrique autres fonds propres)', 'minimal', '22'),
('231', 'Immobilisations corporelles en cours', 'minimal', '23'),
('232', 'Immobilisations incorporelles en cours', 'minimal', '23'),
('237', 'Avances et acomptes versés sur commandes d''immobilisations incorporelles', 'minimal', '23'),
('238', 'Avances et acomptes versés sur commandes d''immobilisations corporelles', 'minimal', '23'),
('261', 'Titres de participation', 'minimal', '26'),
('262', 'Titres évalués par équivalence', 'minimal', '26'),
('266', 'Autres formes de participation', 'minimal', '26'),
('267', 'Créances rattachées à des participations', 'minimal', '26'),
('268', 'Créances rattachées à des sociétés en participation', 'minimal', '26'),
('269', 'Versements restant à effectuer sur titres de participation non libérés', 'minimal', '26'),
('271', 'Titres immobilisés autres que les titres immobilisés de l''activité de portefeuille (droit de propriété)', 'minimal', '27'),
('272', 'Titres immobilisés (droit de créance)', 'minimal', '27'),
('273', 'Titres immobilisés de l''activité de portefeuille', 'minimal', '27'),
('274', 'Prêts', 'minimal', '27'),
('275', 'Dépôts et cautionnements versés', 'minimal', '27'),
('276', 'Autres créances immobilisées', 'minimal', '27'),
('277', 'Actions propres ou parts propres', 'minimal', '27'),
('278', 'Mali de fusion sur actifs financiers', 'facultatif', '27'),
('279', 'Versements restant à effectuer sur titres immobilisés non libérés', 'minimal', '27'),
('280', 'Amortissements des immobilisations incorporelles et des frais d’établissement (même ventilation que celle du compte 20)', 'minimal', '28'),
('281', 'Amortissements des immobilisations corporelles (même ventilation que celle du compte 21)', 'minimal', '28'),
('282', 'Amortissements des immobilisations mises en concession', 'minimal', '28'),
('290', 'Dépréciations des immobilisations incorporelles', 'minimal', '29'),
('291', 'Dépréciations des immobilisations corporelles', 'minimal', '29'),
('292', 'Dépréciations des immobilisations mises en concession', 'minimal', '29'),
('293', 'Dépréciations des immobilisations en cours', 'minimal', '29'),
('296', 'Dépréciations des participations et créances rattachées à des participations', 'minimal', '29'),
('297', 'Dépréciations des autres immobilisations financières', 'minimal', '29'),
('321', 'Matières consommables', 'minimal', '32'),
('322', 'Fournitures consommables', 'minimal', '32'),
('326', 'Emballages', 'minimal', '32'),
('331', 'Produits en cours', 'minimal', '33'),
('335', 'Travaux en cours', 'minimal', '33'),
('341', 'Études en cours', 'minimal', '34'),
('345', 'Prestations de services en cours', 'minimal', '34'),
('351', 'Produits intermédiaires', 'minimal', '35'),
('355', 'Produits finis', 'minimal', '35'),
('358', 'Produits résiduels ou matières de récupération', 'minimal', '35'),
('391', 'Dépréciations des matières premières et fournitures', 'minimal', '39'),
('392', 'Dépréciations des autres approvisionnements', 'minimal', '39'),
('393', 'Dépréciations des en-cours de production de biens', 'minimal', '39'),
('394', 'Dépréciations des en-cours de production de services', 'minimal', '39'),
('395', 'Dépréciations des stocks de produits', 'minimal', '39'),
('397', 'Dépréciations des stocks de marchandises', 'minimal', '39'),
('401', 'Fournisseurs', 'minimal', '40'),
('403', 'Fournisseurs - Effets à payer', 'minimal', '40'),
('404', 'Fournisseurs d''immobilisations', 'minimal', '40'),
('405', 'Fournisseurs d''immobilisations - Effets à payer', 'minimal', '40'),
('408', 'Fournisseurs - Factures non parvenues', 'minimal', '40'),
('409', 'Fournisseurs débiteurs', 'minimal', '40'),
('411', 'Clients', 'minimal', '41'),
('413', 'Clients - Effets à recevoir', 'minimal', '41'),
('416', 'Clients douteux ou litigieux', 'minimal', '41'),
('418', 'Clients - Produits non encore facturés', 'minimal', '41'),
('419', 'Clients créditeurs', 'minimal', '41'),
('421', 'Personnel - Rémunérations dues', 'minimal', '42'),
('422', 'Comité social et économique', 'minimal', '42'),
('424', 'Participation des salariés aux résultats', 'minimal', '42'),
('425', 'Personnel - Avances et acomptes et autres comptes débiteurs', 'minimal', '42'),
('426', 'Personnel - Dépôts', 'minimal', '42'),
('427', 'Personnel - Oppositions', 'minimal', '42'),
('428', 'Personnel - Charges à payer', 'minimal', '42'),
('431', 'Sécurité sociale', 'minimal', '43'),
('437', 'Autres organismes sociaux', 'minimal', '43'),
('438', 'Organismes sociaux - Charges à payer', 'minimal', '43'),
('439', 'Organismes sociaux - Produits à recevoir', 'minimal', '43'),
('441', 'État - Subventions et aides à recevoir', 'minimal', '44'),
('442', 'Contributions, impôts et taxes recouvrés pour le compte de l''État', 'minimal', '44'),
('444', 'État - Impôts sur les bénéfices', 'minimal', '44'),
('445', 'État - Taxes sur le chiffre d''affaires', 'minimal', '44'),
('446', 'Obligations cautionnées', 'minimal', '44'),
('447', 'Autres impôts, taxes et versements assimilés', 'minimal', '44'),
('448', 'État - Charges à payer et produits à recevoir', 'minimal', '44'),
('449', 'Quotas d’émission à acquérir', 'facultatif', '44'),
('451', 'Groupe', 'minimal', '45'),
('455', 'Associés - Comptes courants', 'minimal', '45'),
('456', 'Associés - Opérations sur le capital', 'minimal', '45'),
('457', 'Associés - Dividendes à payer', 'minimal', '45'),
('458', 'Associés - Opérations faites en commun et en GIE', 'minimal', '45'),
('462', 'Créances sur cessions d''immobilisations', 'minimal', '46'),
('464', 'Dettes sur acquisitions de valeurs mobilières de placement', 'minimal', '46'),
('465', 'Créances sur cessions de valeurs mobilières de placement', 'minimal', '46'),
('467', 'Divers comptes débiteurs et produits à recevoir', 'minimal', '46'),
('468', 'Divers comptes créditeurs et charges à payer', 'minimal', '46'),
('471', 'Comptes d''attente', 'facultatif', '47'),
('472', 'Comptes d''attente', 'facultatif', '47'),
('473', 'Comptes d''attente', 'facultatif', '47'),
('474', 'Différences d’évaluation – Actif', 'minimal', '47'),
('475', 'Différences d’évaluation – Passif', 'minimal', '47'),
('476', 'Différence de conversion - Actif', 'minimal', '47'),
('477', 'Différences de conversion - Passif', 'minimal', '47'),
('478', 'Autres comptes transitoires', 'minimal', '47'),
('481', 'Frais d’émission des emprunts', 'minimal', '48'),
('486', 'Charges constatées d''avance', 'minimal', '48'),
('487', 'Produits constatés d''avance', 'minimal', '48'),
('488', 'Comptes de répartition périodique des charges et des produits', 'facultatif', '48'),
('491', 'Dépréciations des comptes de clients', 'minimal', '49'),
('495', 'Dépréciations des comptes du groupe et des associés', 'minimal', '49'),
('496', 'Dépréciations des comptes de débiteurs divers', 'minimal', '49'),
('502', 'Actions propres', 'minimal', '50'),
('503', 'Actions', 'minimal', '50'),
('504', 'Autres titres conférant un droit de propriété', 'minimal', '50')
ON CONFLICT (number) DO NOTHING;