INSERT INTO compta.liasse_cells_2033 (cell_id, label, form, pcg_roots, ordinal) VALUES
('FL', 'Chiffre d''affaires nets', '2033-B', NULL, 1),
('FM', 'Production stockée', '2033-B', NULL, 2),
('FN', 'Production immobilisée', '2033-B', NULL, 3),
('FO', 'Subvention d''exploitation', '2033-B', NULL, 4),
('FP', 'Reprises sur amortissements et provisions, transfert de charges', '2033-B', NULL, 5),
('FQ', 'Autres produits', '2033-B', NULL, 6),
('FR', 'Total des produits d''exploitation', '2033-B', NULL, 7),
('FS', 'Achats de marchandises (y compris droits de douane)', '2033-B', NULL, 8),
('FT', 'Variation de stock (marchandises)', '2033-B', NULL, 9),
('FU', 'Achats de matières premières et autres approvisionnements (y compris droits de douane)', '2033-B', NULL, 10),
('FV', 'Variation de stock (matières premières et approvisionnements)', '2033-B', NULL, 11),
('FW', 'Autres achats et charges externes ', '2033-B', NULL, 12),
('FX', 'Impôts, taxes, versements assimilés', '2033-B', NULL, 13),
('FY', 'Salaires et traitements', '2033-B', NULL, 14),
('FZ', 'Charges sociales ', '2033-B', NULL, 15),
('GA', 'DOTATIONS D''EXPLOITATION', '2033-B', NULL, 16),
('GB', '', '2033-B', NULL, 17),
('GC', '', '2033-B', NULL, 18),
('GD', '', '2033-B', NULL, 19),
('GE', 'Autres charges', '2033-B', NULL, 20),
('GF', 'Total des charges d''exploitation', '2033-B', NULL, 21),
('GG', 'RÉSULTAT D''EXPLOITATION ', '2033-B', NULL, 22),
('GH', 'Bénéfice attribué ou perte transférée', '2033-B', NULL, 23),
('GI', 'Perte supportée ou bénéfice transféré', '2033-B', NULL, 24),
('GJ', 'Produits financiers de participations', '2033-B', NULL, 25),
('GK', 'Produits des autres valeurs mobilières et créances de l''actif immobilisé', '2033-B', NULL, 26),
('GL', 'Autres intérêts et produits assimilés', '2033-B', NULL, 27),
('GM', 'Reprises sur provisions et transfert de charges', '2033-B', NULL, 28),
('GN', 'Différences positives de change', '2033-B', NULL, 29),
('GO', 'Produits nets sur cessions de valeurs mobilières de placement', '2033-B', NULL, 30),
('GP', 'Total des produits financiers', '2033-B', NULL, 31),
('GQ', 'Dotations financières aux amortissements et provisions', '2033-B', NULL, 32),
('GR', 'Intérêts et charges assimilées', '2033-B', NULL, 33),
('GS', 'Différence négative de change', '2033-B', NULL, 34),
('GT', 'Charges nettes sur cession de valeurs mobilières de placement', '2033-B', NULL, 35),
('GU', 'Total des charges financières', '2033-B', NULL, 36),
('GV', 'RÉSULTAT FINANCIER', '2033-B', NULL, 37),
('GW', 'RÉSULTAT COURANT AVANT IMPÔTS', '2033-B', NULL, 38),
('HA', 'Produits exceptionnels sur opérations de gestion', '2033-B', NULL, 39),
('HB', 'Produits exceptionnels sur opérations en capital', '2033-B', NULL, 40),
('HC', 'Reprises sur provisions et transfert de charges', '2033-B', NULL, 41),
('HD', 'Total des produits exceptionnels', '2033-B', NULL, 42),
('HE', 'Charges exceptionnelles sur opérations de gestion ', '2033-B', NULL, 43),
('HF', 'Charges exceptionnelles sur opérations en capital', '2033-B', NULL, 44),
('HG', 'Dotations exceptionnelles aux amortissements et provisions', '2033-B', NULL, 45),
('HH', 'Total des charges exceptionnelles ', '2033-B', NULL, 46),
('HI', 'RÉSULTAT EXCEPTIONNEL', '2033-B', NULL, 47),
('HJ', ' Participation des salariés aux résultats de l''entreprise', '2033-B', NULL, 48),
('HK', ' Impôts sur les bénéfices', '2033-B', NULL, 49),
('HL', 'TOTAL DES PRODUITS', '2033-B', NULL, 50),
('HM', 'TOTAL DES CHARGES', '2033-B', NULL, 51),
('HN', 'BÉNÉFICE OU PERTE (Total des produits - total des charges)', '2033-B', NULL, 52)
ON CONFLICT (cell_id) DO NOTHING;